### ISSUE TITLE
公众号5秒限制

### ISSUE THREAD

**Issue by tiancaik** [ToryPan/ChatGPT_WeChat#1]
tokens = ['Bearer sk-XXX1','Bearer sk-XXX2']
这里要填啥。还有 不用填apikey吗

**Comment by ToryPan** [comment]
这里就是填写openai的apikey

**Comment by ToryPan** [comment]
5秒限制的处理方法是将发送到openai的请求放在全局变量中，超过5s后，微信端发送的第二次或第三次的请求就会处于等候状态，直到全局变量有结果了，就将结果返回微信发送过来的最新请求。所以最长可以15s等候，不过在实际使用中发现，把[max_tokens](https://github.com/ToryPan/ChatGPT_WeChat/find-definition?q=max_tokens&blob_path=myflask.py&ref=main&language=Python&row=16&col=0&code_nav_context=BLOB_VIEW)这个参数设置小点的话，返回的速度会更快。

**Comment by tiancaik** [comment]
好的，多谢多谢，已经部署了
但是好像访问不到，有个莫斯科的ip是你的吗

**Comment by ToryPan** [comment]
什么访问不到呢？应该不是，没有莫斯科的ip

**Comment by tiancaik** [comment]
我flaskrun以后，在微信上给公众号发消息还是不行。shell里面老是返回404
我自己本来有一个部署了3.5turbo的公众号，但是没解决5s限制和连续问答的问题。
我下周能加一下你吗，请教一下

**Comment by ToryPan** [comment]
那先看看服务器能不能正常的发送请求到openai呢。可以交流一下~扣扣：510105684
