### ISSUE TITLE
微信基本配置时显示Token验证失败

### ISSUE THREAD

**Issue by Joelsenior** [ToryPan/ChatGPT_WeChat#14]

**Comment by bobzhen8** [comment]
我的也是这样

**Comment by Joelsenior** [comment]
> 我的也是这样

你试试url带上/wechat/,再不行把验证部分注释掉：    if request.method == 'GET':return request.args.get('echostr')
我是这个解决的，不行的话加我微信seniorfd

**Comment by ToryPan** [comment]
> > 我的也是这样
> 
> 你试试url带上/wechat/,再不行把验证部分注释掉： if request.method == 'GET':return request.args.get('echostr') 我是这个解决的，不行的话加我微信seniorfd

必须带上/wechat/。还有如果服务器使用nginx进行内网转发，需要设置ip_detection为False

**Comment by Joelsenior** [comment]
解决了，在微信公众号服务器配置添加/wechat/
