### ISSUE TITLE
服务启动，但微信公众号端始终无法验证通过

### ISSUE THREAD

**Issue by gooderek** [ToryPan/ChatGPT_WeChat#4]
一直显示token验证失败，搞个子目录会不会解决这个问题，比如example.com/wx ?。另外，为啥有的项目只需要token，您这个项目需要appid，secret等？

**Comment by ToryPan** [comment]
代码里面写的本身就在一个子url里面，example.com/wechat/。appid，secret这个是用于上传语音素材的，如果不开语音服务，可以随便填( 我等下再优化一下，不开语音服务就不用填这两个参数)

**Comment by ToryPan** [comment]
已修复appid，secret必填的问题，麻烦更新再试

**Comment by gooderek** [comment]
是我ipv6的问题，白名单过不了。谢谢大佬
