### ISSUE TITLE
请求超时，请稍后再试！

### ISSUE THREAD

**Issue by gdphuang** [ToryPan/ChatGPT_WeChat#5]
超时频率非常高，严重影响体验，不知道是服务器延时的原因还是ChatGPT的原因。

**Comment by ToryPan** [comment]
ChatGPT的原因吧，昨天和今天请求响应时间大幅度延长，还频繁提示overload，之前也有类似情况，不过过几天就好了。我昨天单独用接口测试了一下请求100token的用时平均超过20s。现在的解决方案可能只有减少max_token，唉，这就是没有认证的公众号的烦恼。

**Comment by ToryPan** [comment]
今天ChatGPT响应速度已经恢复，测试最佳的token数量：openai-max_tokens: 180，azure-max_token: 100，可以参考这个填写。

**Comment by ToryPan** [comment]
sry，又变慢了一点，现在我改成了：openai-max_tokens: 110，azure-max_token: 60

**Comment by tvgh** [comment]
> ChatGPT的原因吧，昨天和今天请求响应时间大幅度延长，还频繁提示overload，之前也有类似情况，不过过几天就好了。我昨天单独用接口测试了一下请求100token的用时平均超过20s。现在的解决方案可能只有减少max_token，唉，这就是没有认证的公众号的烦恼。

大佬能不能开发下客服接口,需要的话我提供测试的认证企业服务号

**Comment by gdphuang** [comment]
安装了sseclient-py还是报这个错。

name 'SSEClient' is not defined

**Comment by gooderek** [comment]
我添加了付费方式，已经开始付费了。目前似乎没有速度上的影响。不过，那啥，使用poe的逆向api岂不是更爽？

**Comment by ToryPan** [comment]
谢谢~
