### ISSUE TITLE
内部服务器错误

### ISSUE THREAD

**Issue by dhf2587154870** [ToryPan/ChatGPT_WeChat#8]
![image](https://user-images.githubusercontent.com/92639256/233831534-b1b2aa1a-5858-444a-9cc6-0c25337daacf.png)
![image](https://user-images.githubusercontent.com/92639256/233831560-8c84a4ce-561c-42c2-bc46-9b7b329d79ef.png)
大佬还是不行 按照你的指示我把代码取消注释：
@app.route("/")
def hello():
    return "Hello test!"
并且在浏览器输入服务器ip/wechat/打开显示内部服务器错误
服务器遇到内部错误，无法完成您的请求。服务器过载或应用程序中存在错误。

**Comment by dhf2587154870** [comment]
![image](https://user-images.githubusercontent.com/92639256/233831845-b39048dc-dee1-445a-8fa9-6af344d8dc09.png)
![image](https://user-images.githubusercontent.com/92639256/233831873-8590262c-d5a4-4753-bc52-de5f46f65205.png)

**Comment by ToryPan** [comment]
在[gptManage.py](https://github.com/ToryPan/ChatGPT_WeChat/blob/main/gptManage.py)文件里面加上这句吧：`from sseclient import SSEClient`
![image](https://user-images.githubusercontent.com/59463198/233832241-cbe8eaaa-bf21-4c5f-a089-05286d53df88.png)

**Comment by dhf2587154870** [comment]
![image](https://user-images.githubusercontent.com/92639256/233832607-53265588-8e36-413d-8b6d-04725cde28e5.png)
加了运行成这样

**Comment by ToryPan** [comment]
> ![image](https://user-images.githubusercontent.com/92639256/233831534-b1b2aa1a-5858-444a-9cc6-0c25337daacf.png) ![image](https://user-images.githubusercontent.com/92639256/233831560-8c84a4ce-561c-42c2-bc46-9b7b329d79ef.png) 大佬还是不行 按照你的指示我把代码取消注释： @app.route("/") def hello(): return "Hello test!" 并且在浏览器输入服务器ip/wechat/打开显示内部服务器错误 服务器遇到内部错误，无法完成您的请求。服务器过载或应用程序中存在错误。

https://github.com/ToryPan/ChatGPT_WeChat/issues/3#issuecomment-1518929721
这儿已经说得很清楚了，浏览器访问直接用ip，可以用于测试你的服务是否启动。ip/wechat/是写给微信服务器的，直接在浏览器打开肯定会报错！

**Comment by ToryPan** [comment]
> ![image](https://user-images.githubusercontent.com/92639256/233832607-53265588-8e36-413d-8b6d-04725cde28e5.png) 加了运行成这样

这个模块安装了吗：sseclient-py

**Comment by dhf2587154870** [comment]
> > ![图像](https://user-images.githubusercontent.com/92639256/233832607-53265588-8e36-413d-8b6d-04725cde28e5.png)加了运行成这样
> 
> 这个模块安装了吗：sseclient-py

安装了 运行公众号废了
![image](https://user-images.githubusercontent.com/92639256/233832862-fa76e339-0653-4a51-8643-214bd84065bd.png)

**Comment by ToryPan** [comment]
如果你方便的话qq联系吧：510105684

**Comment by dhf2587154870** [comment]
又变成这样了
![image](https://user-images.githubusercontent.com/92639256/233832964-6c0a753f-84de-477f-aa47-7122f55aba1e.png)

**Comment by dhf2587154870** [comment]
> 如果你方便的话qq联系吧：510105684

加了
